language: csharp
mono: none
solution: NetCoreTempSolution.sln
dotnet: 2.1
install:
 - dotnet restore NetCoreTempSolution.sln
script: 
 - dotnet build
 - dotnet test WebAppCore.IntegrationTests/WebAppCore.IntegrationTests.csproj