language: csharp
mono: none
dotnet: 2.1
script: 
 - dotnet build NetCoreTempSolution.sln
 - dotnet test WebAppCore.IntegrationTests/WebAppCore.IntegrationTests.csproj
 - dotnet test ConsoleAppCoreTest/ConsoleAppCoreTest.csproj