language: csharp
mono: none
solution: NetCoreTempSolution.sln
dotnet: 2.1
install:
 - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script: 
 - dotnet restore NetCoreTempSolution.sln
 - xbuild /p:Configuration=Release NetCoreTempSolution.sln
 - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./WebAppCore.IntegrationTests/bin/Release/netcoreapp2.1/WebAppCore.IntegrationTests.dll