dist: xenial
language: csharp
mono: none
dotnet: 3.1.101
script: 
 - dotnet build NetCoreTempSolution.sln
 - dotnet test WebAppCore.IntegrationTests/WebAppCore.IntegrationTests.csproj
 - dotnet test ConsoleAppCore.UnitTests/ConsoleAppCore.UnitTests.csproj
 - dotnet test WebAppCore.UnitTests/WebAppCore.UnitTests.csproj